[package]
name = "target-lexicon"
version = "0.0.1"
authors = ["Dan Gohman <sunfish@mozilla.com>"]
description = "Targeting utilities for compilers and related tools"
keywords = ["target", "host", "triple", "compiler", "jit"]
documentation = "https://docs.rs/target-lexicon/"
repository = "https://github.com/cretonne/target-lexicon"
readme = "README.md"
# When cargo is updated to support SPDX 3.1, we can uncomment this.
#license = "Apache-2.0 WITH LLVM-exception"
license-file = "LICENSE"

[dependencies]
failure = { version = "0.1.1", default-features = false, features = ["derive"] }
failure_derive = { version = "0.1.1", default-features = false }

[build-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = []

[badges]
maintenance = { status = "passively-maintained" }
travis-ci = { repository = "cretonne/target-lexicon" }
